# coding: utf8
from __future__ import unicode_literals


_exc = {
    # Gírias e abreviações
    "abç": "abraço",
    "aham": "sim",
    "att": "atenciosamente"
    "bj": "beijo",
    "bjs": "beijos",
    "bixo": "bicho",
    "blz": "beleza",
    "br": "brasileiro",
    "brinks": "brincadeira",
    "brinkz": "brincadeira",
    "ctz": "certeza",
    "eh": "é",
    "fds": "fim de semana",
    "fdp": "filho da puta",
    "flw": "tchau",
    "fodase": "foda-se",
    "haah": "risos",
    "haha": "risos",
    "hahah": "risos",
    "hahaha": "risos",
    "hahahah": "risos",
    "hahahaha": "risos",
    "hahahahah": "risos",
    "hahahahaha": "risos",
    "hahahahahaha": "risos",
    "hahahahahahah": "risos",
    "hj": "hoje",
    "hm": "ok",
    "hmm": "ok",
    "hr": "hora",
    "hrs": "horas",
    "kk": "risos",
    "kkk": "risos",
    "kkkk": "risos",
    "kkkkk": "risos",
    "kkkkkk": "risos",
    "kkkkkkk": "risos",
    "kkkkkkkk": "risos",
    "kkkkkkkkk": "risos",
    "kkkkkkkkkk": "risos",
    "kkkkkkkkkkk": "risos",
    "kkkkkkkkkkkk": "risos",
    "kkkkkkkkkkkkk": "risos",
    "mds": "meu deus",
    "msm": "mesmo",
    "mto": "muito",
    "ñ": "não",
    "nao": "não",
    "pfv": "por favor",
    "pfvr": "por favor",
    "pq": "porque",
    "pra": "para",
    "pro": "para o",
    "q": "que",
    "qq": "que é que",
    "rlx": "relaxa",
    "rs": "risos",
    "rsrs": "risos",
    "rsrsrs": "risos",
    "rsrsrsrs": "risos",
    "rsrsrsrsrs": "risos",
    "rsrsrsrsrsrs": "risos",
    "sdd": "saudade",
    "sdds": "saudades",
    "sr": "senhor",
    "sra": "senhora",
    "tb": "também",
    "tbm": "também",
    "td": "tudo",
    "tmb": "também",
    "tmj": "estamos juntos",
    "topz": "legal",
    "topzera": "legal",
    "tqr": "tem que respeitar",
    "uhum": "sim",
    "vc": "você",
    "vdd": "verdade",
    "vlw": "obrigado",

    # Símbolos
    "R$": "$"
}

NORM_EXCEPTIONS = {}

for string, norm in _exc.items():
    NORM_EXCEPTIONS[string] = norm
    NORM_EXCEPTIONS[string.title()] = norm