# coding: utf8
from __future__ import unicode_literals


_exc = {
    # Gírias e abreviações
    "abç": "abraço",
    "abrç": "abraço",
    "aham": "sim",
    "ahan": "sim",
    "anham": "sim",
    "anhan": "sim",
    "ateh": "até",
    "att": "atenciosamente",
    "bj": "beijo",
    "bjo": "beijo",
    "bjos": "beijo",
    "bjs": "beijos",
    "bixo": "bicho",
    "blz": "beleza",
    "br": "brasileiro",
    "brinks": "brincadeira",
    "brinkz": "brincadeira",
    "ctz": "certeza",
    "eh": "é",
    "ei": "olá",
    "fds": "fim de semana",
    "fdp": "filho da puta",
    "flw": "tchau",
    "fodase": "foda-se",
    "género": "gênero",
    "haah": "riso",
    "haha": "riso",
    "hahah": "riso",
    "hahaha": "riso",
    "hahahah": "riso",
    "hahahaha": "riso",
    "hahahahah": "riso",
    "hahahahaha": "riso",
    "hahahahahaha": "riso",
    "hahahahahahah": "riso",
    "hey": "olá",
    "hj": "hoje",
    "hm": "ok",
    "hmm": "ok",
    "hr": "hora",
    "hrs": "horas",
    "idéia": "ideia",
    "kk": "riso",
    "kkk": "riso",
    "kkkk": "riso",
    "kkkkk": "riso",
    "kkkkkk": "riso",
    "kkkkkkk": "riso",
    "kkkkkkkk": "riso",
    "kkkkkkkkk": "riso",
    "kkkkkkkkkk": "riso",
    "kkkkkkkkkkk": "riso",
    "kkkkkkkkkkkk": "riso",
    "kkkkkkkkkkkkk": "riso",
    "mds": "meu deus",
    "msm": "mesmo",
    "mto": "muito",
    "ñ": "não",
    "nao": "não",
    "oie": "olá",
    "opa": "olá",
    "óptimo": "ótimo",
    "pfv": "por favor",
    "pfvr": "por favor",
    "pq": "porque",
    "pra": "para",
    "pro": "para o",
    "q": "que",
    "qq": "que é que",
    "rlx": "relaxa",
    "rs": "riso",
    "rsrs": "riso",
    "rsrsrs": "riso",
    "rsrsrsrs": "riso",
    "rsrsrsrsrs": "riso",
    "rsrsrsrsrsrs": "riso",
    "sdd": "saudade",
    "sdds": "saudades",
    "sr": "senhor",
    "sra": "senhora",
    "tb": "também",
    "tbm": "também",
    "td": "tudo",
    "tmb": "também",
    "tmj": "estamos juntos",
    "topz": "legal",
    "topzera": "legal",
    "tqr": "tem que respeitar",
    "uhum": "sim",
    "uhun": "sim",
    "vc": "você",
    "vdd": "verdade",
    "vlw": "obrigado",
    # Escritas diferentes
    "cota": "quota",
    "quatorze": "catorze",
    "quatrilhão": "quadrilhão",
    "quatrilhões": "quadrilhões",
    # Símbolos
    "R$": "$"
}

NORM_EXCEPTIONS = {}

for string, norm in _exc.items():
    NORM_EXCEPTIONS[string] = norm
    NORM_EXCEPTIONS[string.title()] = norm